title: Guia do DCC
description: Tudo que você precisa saber sobre o DCC da UFJF, com dicas e explicações que vão te ajudar a se adaptar ao curso.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
